MAX_TMOUT_GAME_START = 10
DEBUG_FLAG = True

SLEEP_TIME_VERY_VERY_SHORT = 0.05
SLEEP_TIME_VERY_SHORT = 0.1
SLEEP_TIME_SHORT = 0.3
SLEEP_TIME_MIDDLE = 0.5
SLEEP_TIME_NORMAL = 1
SLEEP_TIME_LONG = 2
SLEEP_TIME_VERY_LONG = 5
SLEEP_TIME_VERY_VERY_LONG = 10

